### ISSUE TITLE
epic: Global ingress support

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/contrib-tmc#32]
### TL;DR

Implement a global ingress spanning several physical clusters than can be used with KCP workloads spread amonf several SyncTargets

### Progress tracking <a href="#progress-tracking" id="progress-tracking">#</a>

EPIC detailed issues and overall progress can be tracked with the following [project view](https://github.com/orgs/kcp-dev/projects/1/views/56)

### Stories

- [ ] kcp-dev/kcp#2914
- [ ] kcp-dev/kcp-glbc#502
- [ ] kcp-dev/contrib-tmc#31
