### ISSUE TITLE
epic: Multiple shard support in TMC

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/contrib-tmc#47]
### TL;DR

Implement the support of multiple shards in the TMC components

### Progress tracking <a href="#progress-tracking" id="progress-tracking">#</a>

EPIC detailed issues and overall progress can be tracked with the following [project view](https://github.com/orgs/kcp-dev/projects/1/views/53)

### Stories

- [x] kcp-dev/kcp#2832
- [x] kcp-dev/kcp#2943
- [x] kcp-dev/kcp#2900
- [ ] kcp-dev/contrib-tmc#45
- [ ] kcp-dev/contrib-tmc#44
- [ ] kcp-dev/kcp#2833
- [ ] Think about what it means for a coordination controller to be shard-aware
