### ISSUE TITLE
epic: Split workloads code from control plane code

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/contrib-tmc#76]
### Feature Description

Enhancement Link: https://github.com/kcp-dev/kcp/blob/main/docs/enhancements/0001_project_enhancements.md

See [this section](https://github.com/kcp-dev/kcp/blob/main/docs/enhancements/0001_project_enhancements.md#split-the-workloads-project-from-the-control-plane) for background.

### Stories

- [ ] [Create new workloads repository](https://github.com/kcp-dev/kcp/issues/2411)
- [ ] [Move source code](https://github.com/kcp-dev/kcp/issues/2412)
- [ ] [Ensure there is appropriate build/install documentation for workloads](https://github.com/kcp-dev/contrib-tmc/issues/73)
- [ ] [Ensure there is appropriate CI coverage for workloads](https://github.com/kcp-dev/contrib-tmc/issues/72)
